### ISSUE TITLE
Conda Forge Python 3.6 issue

### ISSUE THREAD

**Issue by mickohara23** [scikit-learn-contrib/hdbscan#104]
Using lastest version of Anaconda, which is using python 3.6.
Is hdbscan unavailable for python 3.6

UnsatisfiableError: The following specifications were found to be in conflict:
  - hdbscan -> python 3.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by lmcinnes** [comment]
I'm not so familiar with the conda-forge build infrastructure or how to use
it, I just know it magically works most of the time. I'll try to look into
this.

**Comment by jope35** [comment]
Also getting the same error message with conda forge

'''
conda install -c conda-forge hdbscan

Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - hdbscan -> python 3.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
'''

when using 
'''
pip install hdbscan
'''

the error is as follows


'''
Collecting hdbscan
  Using cached hdbscan-0.8.10.tar.gz
Requirement already satisfied: scikit-learn>=0.16 in c:\users\jdetheije\appdata\local\continuum\anaconda3\lib\site-packages (from hdbscan)
Requirement already satisfied: cython>=0.17 in c:\users\jdetheije\appdata\local\continuum\anaconda3\lib\site-packages (from hdbscan)
Building wheels for collected packages: hdbscan
  Running setup.py bdist_wheel for hdbscan ... error
  Complete output from command C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JDETHE~1\\AppData\\Local\\Temp\\pip-build-6qu5iatn\\hdbscan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\JDETHE~1\AppData\Local\Temp\tmp6h_q5ienpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\hdbscan_.py -> build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\plots.py -> build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\prediction.py -> build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\validity.py -> build\lib.win-amd64-3.6\hdbscan
  copying hdbscan\__init__.py -> build\lib.win-amd64-3.6\hdbscan
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JDETHE~1\AppData\Local\Temp\pip-build-6qu5iatn\hdbscan\setup.py", line 88, in <module>
      setup(**configuration)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
      _build_ext.build_ext.run(self)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
      force=self.force)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 282, in __init__
      CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
      self.dll_libraries = get_msvcr()
    File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
      raise ValueError("Unknown MS Compiler version %s " % msc_ver)
  ValueError: Unknown MS Compiler version 1900

  ----------------------------------------
  Failed building wheel for hdbscan
  Running setup.py clean for hdbscan
Failed to build hdbscan
Installing collected packages: hdbscan
  Running setup.py install for hdbscan ... error
    Complete output from command C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JDETHE~1\\AppData\\Local\\Temp\\pip-build-6qu5iatn\\hdbscan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JDETHE~1\AppData\Local\Temp\pip-_ijg_fdk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\hdbscan_.py -> build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\plots.py -> build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\prediction.py -> build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\validity.py -> build\lib.win-amd64-3.6\hdbscan
    copying hdbscan\__init__.py -> build\lib.win-amd64-3.6\hdbscan
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JDETHE~1\AppData\Local\Temp\pip-build-6qu5iatn\hdbscan\setup.py", line 88, in <module>
        setup(**configuration)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
        self.dll_libraries = get_msvcr()
      File "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
        raise ValueError("Unknown MS Compiler version %s " % msc_ver)
    ValueError: Unknown MS Compiler version 1900

    ----------------------------------------
Command "C:\Users\JdeTheije\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JDETHE~1\\AppData\\Local\\Temp\\pip-build-6qu5iatn\\hdbscan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JDETHE~1\AppData\Local\Temp\pip-_ijg_fdk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\JDETHE~1\AppData\Local\Temp\pip-build-6qu5iatn\hdbscan\
'''

**Comment by lmcinnes** [comment]
I think the pip problems are the usual issue of compilation being difficult on Windows. Conda-forge was the solution to that, but it doesn't seem to be doing the job for Python 3.6. I think, but don't know, that it should be a matter of getting conda-smithy to rerender the feedstock. Hopefully that will work.

**Comment by jope35** [comment]
i am a bit new to the conda-smithy thing. is that something that i can do or the maintainers of the project? @lmcinnes

**Comment by Vbolwerk** [comment]
I'm getting the same error message as @jope35 when trying to install using conda-forge, but I am not familiar with conda-smithy either. Could you elaborate @lmcinnes? Thanks!

**Comment by lmcinnes** [comment]
Sorry all; that was a note as much to me as anyone that I need to try and get conda-forge to update and support python 3.6. I son't really know how to do that, so I'm trying a few things. Bear with me.

**Comment by lmcinnes** [comment]
Alright, I think I've gt this working now. It may take a while to get through the system, so try tomorrow and let me know if it is now working.

**Comment by jope35** [comment]
many thanks to you @lmcinnes 

it seems to install and work excellent using the `conda install -c conda-forge hdbscan` command

**Comment by Vbolwerk** [comment]
Great, thanks @lmcinnes

**Comment by lmcinnes** [comment]
Great, glad it is working now!
