### ISSUE TITLE
error in installing hdbscan in MacOs

### ISSUE THREAD

**Issue by taushifkhan** [scikit-learn-contrib/hdbscan#211]
:hdbscan-master$ python -m nose -s hdbscan
E
======================================================================
ERROR: Failure: ImportError (No module named _hdbscan_linkage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/taushif/Softwares/hdbscan/hdbscan-master/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/Users/taushif/Softwares/hdbscan/hdbscan-master/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
ImportError: No module named _hdbscan_linkage

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by lmcinnes** [comment]
I'm not really sure what the issue is there. Current travis builds are green, and it builds and runs for me successfully locally on a Mac. I would strongly suggest trying using conda-forge or PyPI as that will eliminate some of the build/compiler issues.

**Comment by FinLouarn** [comment]
I got the same error on Linux, whether I use conda-forge, pip or build it with `python setup.py install`

**Comment by lmcinnes** [comment]
@FinLouarn That sounds disconcerting -- it would be bad if current PyPI and conda-forge packages are broken. Let me run some tests and see if I can reproduce this.

**Comment by lmcinnes** [comment]
It seems to be working fine for me. Potentially if you are in the cloned directory and you have your PYTHONPATH set to favour '.' (which may the the default in many cases) then it is going to (incorrectly) look in the hdbscan directory immediately in the current directory. If you run this again from a *different* directory then it should work properly if hat was the problem.
