### ISSUE TITLE
import hdbscan failure after pip install on linux

### ISSUE THREAD

**Issue by braymp** [scikit-learn-contrib/hdbscan#222]
Recently, I used <code>pip install hdbscan</code> under Python 2.7.11 which was successful. However, upon trying to <code>import hdbscan</code>, I get the following error:
```
Python 2.7.11 (default, Dec 22 2016, 01:51:28) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdbscan
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brayma2/.local/lib/python2.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/brayma2/.local/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/dist_metrics.pxd", line 61, in init hdbscan._hdbscan_linkage (hdbscan/_hdbscan_linkage.c:20936)
ImportError: numpy.core.multiarray failed to import
```
Though it appears to be a numpy error/version mismatch, <code>pip list</code> shows the following:
```
Cython (0.25.2)
numpy (1.11.2)
scikit-learn (0.19.1)
scipy (0.18.1)
```
which satisfies the requirements.txt file.

Furthermore, attempting to compile from source yields the following error (sorry for the length):
```
running install
running bdist_egg
running egg_info
writing requirements to hdbscan.egg-info/requires.txt
writing hdbscan.egg-info/PKG-INFO
writing top-level names to hdbscan.egg-info/top_level.txt
writing dependency_links to hdbscan.egg-info/dependency_links.txt
reading manifest file 'hdbscan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hdbscan.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/robust_single_linkage_.py -> build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/prediction.py -> build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/hdbscan_.py -> build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/validity.py -> build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/__init__.py -> build/lib.linux-x86_64-2.7/hdbscan
copying hdbscan/plots.py -> build/lib.linux-x86_64-2.7/hdbscan
creating build/lib.linux-x86_64-2.7/hdbscan/tests
copying hdbscan/tests/test_hdbscan.py -> build/lib.linux-x86_64-2.7/hdbscan/tests
copying hdbscan/tests/test_rsl.py -> build/lib.linux-x86_64-2.7/hdbscan/tests
copying hdbscan/tests/__init__.py -> build/lib.linux-x86_64-2.7/hdbscan/tests
running build_ext
cythoning hdbscan/_hdbscan_tree.pyx to hdbscan/_hdbscan_tree.c
building 'hdbscan._hdbscan_tree' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/hdbscan
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/_hdbscan_tree.c -o build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_tree.o
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_tree.c:435:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -shared -Wl,-rpath=$ORIGIN/../lib build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_tree.o -L/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/hdbscan/_hdbscan_tree.so
skipping 'hdbscan/_hdbscan_linkage.c' Cython extension (up-to-date)
building 'hdbscan._hdbscan_linkage' extension
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/_hdbscan_linkage.c -o build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_linkage.o
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_linkage.c:274:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_linkage.c:274:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/__multiarray_api.h:1448:1: warning: â€˜_import_arrayâ€™ defined but not used [-Wunused-function]
 _import_array(void)
 ^
gcc -shared -Wl,-rpath=$ORIGIN/../lib build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_linkage.o -L/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/hdbscan/_hdbscan_linkage.so
cythoning hdbscan/_hdbscan_boruvka.pyx to hdbscan/_hdbscan_boruvka.c
building 'hdbscan._hdbscan_boruvka' extension
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/_hdbscan_boruvka.c -o build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_boruvka.o
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_boruvka.c:435:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
hdbscan/_hdbscan_boruvka.c: In function â€˜__pyx_f_7hdbscan_16_hdbscan_boruvka_24BallTreeBoruvkaAlgorithm_dual_tree_traversalâ€™:
hdbscan/_hdbscan_boruvka.c:14509:16: warning: â€˜__pyx_v_new_lower_boundâ€™ may be used uninitialized in this function [-Wmaybe-uninitialized]
     __pyx_t_19 = (__pyx_v_new_lower_bound + (2.0 * __pyx_v_node1_info.radius));
                ^
hdbscan/_hdbscan_boruvka.c:14527:8: warning: â€˜__pyx_v_new_upper_boundâ€™ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (((__pyx_t_19 < __pyx_t_5) != 0)) {
        ^
gcc -shared -Wl,-rpath=$ORIGIN/../lib build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_boruvka.o -L/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/hdbscan/_hdbscan_boruvka.so
skipping 'hdbscan/_hdbscan_reachability.c' Cython extension (up-to-date)
building 'hdbscan._hdbscan_reachability' extension
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/_hdbscan_reachability.c -o build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_reachability.o
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_reachability.c:274:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_hdbscan_reachability.c:274:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/__multiarray_api.h:1448:1: warning: â€˜_import_arrayâ€™ defined but not used [-Wunused-function]
 _import_array(void)
 ^
gcc -shared -Wl,-rpath=$ORIGIN/../lib build/temp.linux-x86_64-2.7/hdbscan/_hdbscan_reachability.o -L/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/hdbscan/_hdbscan_reachability.so
cythoning hdbscan/_prediction_utils.pyx to hdbscan/_prediction_utils.c
building 'hdbscan._prediction_utils' extension
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/_prediction_utils.c -o build/temp.linux-x86_64-2.7/hdbscan/_prediction_utils.o
In file included from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from hdbscan/_prediction_utils.c:435:
/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -shared -Wl,-rpath=$ORIGIN/../lib build/temp.linux-x86_64-2.7/hdbscan/_prediction_utils.o -L/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/hdbscan/_prediction_utils.so
cythoning hdbscan/dist_metrics.pyx to hdbscan/dist_metrics.c

Error compiling Cython file:
------------------------------------------------------------
...

    cdef inline DTYPE_t dist(self, DTYPE_t* x1, DTYPE_t* x2,
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
             ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1138:14: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef inline DTYPE_t dist(self, DTYPE_t* x1, DTYPE_t* x2,
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
             ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1139:14: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    cdef inline DTYPE_t dist(self, DTYPE_t* x1, DTYPE_t* x2,
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
                                 ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1138:34: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef inline DTYPE_t dist(self, DTYPE_t* x1, DTYPE_t* x2,
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
                                 ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1139:34: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
        return self.func(x1arr, x2arr, **self.kwargs)
                       ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1140:24: Coercion from Python not allowed without the GIL

Error compiling Cython file:
------------------------------------------------------------
...
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
        return self.func(x1arr, x2arr, **self.kwargs)
                       ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1140:24: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
        return self.func(x1arr, x2arr, **self.kwargs)
                       ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1140:24: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
                             ITYPE_t size) except -1 with gil:
        cdef np.ndarray x1arr
        cdef np.ndarray x2arr
        x1arr = _buffer_to_ndarray(x1, size)
        x2arr = _buffer_to_ndarray(x2, size)
        return self.func(x1arr, x2arr, **self.kwargs)
                       ^
------------------------------------------------------------

hdbscan/dist_metrics.pyx:1140:24: Constructing Python dict not allowed without gil
building 'hdbscan.dist_metrics' extension
gcc -fno-strict-aliasing -O3 -march=x86-64 -mtune=generic -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/include/python2.7 -I/usr/prog/python/2.7.11-goolf-1.5.14-NX/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -c hdbscan/dist_metrics.c -o build/temp.linux-x86_64-2.7/hdbscan/dist_metrics.o
hdbscan/dist_metrics.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'gcc' failed with exit status 1
```
Any suggestions?

**Comment by lmcinnes** [comment]
I am at a little bit of a loss. Clearly there is some mismatch going on here. The ``dist_metrics.pyx`` is borrowed from Jake Vanderplas' scikit-learn implementation. Do you know if you can compile/run scikit-learn on your current setup? Specifically the KDTree? Otherwise I'm not to sure what the next step is, other than possibly looking at re-installing numpy, which you understandably may not want to do.

**Comment by braymp** [comment]
No apologies needed; thanks for the prompt response!

**Comment by loisaidasam** [comment]
I just ran into this as well working with older frozen dependencies: `hdbscan` at version `0.8.10`

I just wanted to note that the solution for me was upgrading to version `0.8.14`, the first tag that contains these commits.

**Comment by verwindle** [comment]
Got this issue on version 0.8.28. It worked for me on python 3.8.12 with
* numpy==1.21.6
* scikit-learn==1.0.2
Probably, you are to install joblib==1.1 if you encounter an error with cachedir
