### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by SantiagoOrdonez** [scikit-learn-contrib/hdbscan#248]
Hi, 

I have a data set of ~3000000 lat/lng data points and I was hoping to use HDBSCAN. Unfortunately, when I ran it on this data set I got an out of memory error.  I had ran HDBSCAN on a smaller portion of the data set and It worked fine. I am using the haversine metric and thus cannot use the algorithm "prims_kdtree". 

Here is my stack trace: 
Traceback (most recent call last):
  File "create_regions.py", line 167, in <module>
    create_clusters(df, epsilon, 1000, "HDBSCAN")
  File "create_regions.py", line 43, in create_clusters
    labels = clusterer.fit_predict(np.radians(df))
  File "/var/opt/mapworkflows/venv/local/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 876, in fit_predict
    self.fit(X)
  File "/var/opt/mapworkflows/venv/local/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 854, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/var/opt/mapworkflows/venv/local/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 589, in hdbscan
    core_dist_n_jobs, **kwargs)
  File "/var/opt/mapworkflows/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 329, in __call__
    return self.func(*args, **kwargs)
  File "/var/opt/mapworkflows/venv/local/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 285, in _hdbscan_boruvka_balltree
    n_jobs=core_dist_n_jobs, **kwargs)
  File "hdbscan/_hdbscan_boruvka.pyx", line 976, in hdbscan._hdbscan_boruvka.BallTreeBoruvkaAlgorithm.__init__
  File "hdbscan/dist_metrics.pyx", line 398, in hdbscan.dist_metrics.DistanceMetric.pairwise
MemoryError

**Comment by SantiagoOrdonez** [comment]
Thanks Leland. It was my understanding that HDBSCAN could cluster up towards 5M points (https://youtu.be/AgPQ76RIi6A?t=1066). I am running on a 16GB ram machine. Regardless, thanks for the suggestion. I will checkout OPTICS.

**Comment by lmcinnes** [comment]
Large memory SMPs are what you need to get that large. AWS will, for example, provide servers with 1TB of RAM or more. Still, in this case OPTICS may be your best bet.

**Comment by SantiagoOrdonez** [comment]
Sounds good, thanks LeLand.
