### ISSUE TITLE
AttrivbuteError: No prediction data was generated

### ISSUE THREAD

**Issue by mrxiaohe** [scikit-learn-contrib/hdbscan#249]
I trained a HDBSCAN model on a set of data, and would like to use the model to make predictions on new data. I did the following:

`hdbscan.approximate_predict(hdbscan_, data[0])
`
and got the following error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\hdbscan\prediction.py", line 373, in approximate_predict
    if clusterer.prediction_data_ is None:
  File "C:\ProgramData\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 909, in prediction_data_
    raise AttributeError('No prediction data was generated')
AttributeError: No prediction data was generated
```

I wonder what might be the cause of this. Thanks!

**Comment by mrxiaohe** [comment]
I think I found the answer... I should've specified `prediction_data = True`
