### ISSUE TITLE
Import hdbscan ISSUE

### ISSUE THREAD

**Issue by greg2626** [scikit-learn-contrib/hdbscan#258]
Hi,
I have followed all the steps for installing hdbscan, but still I'm getting the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-3f5a460d7435> in <module>
----> 1 import hdbscan

/opt/conda/lib/python3.6/site-packages/hdbscan/__init__.py in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import approximate_predict, membership_vector, all_points_membership_vectors
      5 

/opt/conda/lib/python3.6/site-packages/hdbscan/hdbscan_.py in <module>
     19 from scipy.sparse import csgraph
     20 
---> 21 from ._hdbscan_linkage import (single_linkage,
     22                                mst_linkage_core,
     23                                mst_linkage_core_vector,

hdbscan/_hdbscan_linkage.pyx in init hdbscan._hdbscan_linkage()

AttributeError: type object 'hdbscan._hdbscan_linkage.UnionFind' has no attribute '__reduce_cython__'
```

Does someone knows how to fix it ?
Bests,

**Comment by lmcinnes** [comment]
I have never seen anything quite like that before? Are you installing via conda and conda-forge?

**Comment by mstrejczek** [comment]
Upgrade from numpy==1.15.3 to numpy==1.16.0 fixed the problem for us.

We have used the same set of dependencies for months now, so why it suddenly started to fail remains a mistery.

**Comment by laugh12321** [comment]
I have tried all the methods you said (manual installation, upgrade numpy), but it still doesn't work.

```
import hdbscan
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-47-3f5a460d7435> in <module>
----> 1 import hdbscan

~/anaconda3/lib/python3.7/site-packages/hdbscan/__init__.py in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import approximate_predict, membership_vector, all_points_membership_vectors
      5 

~/anaconda3/lib/python3.7/site-packages/hdbscan/hdbscan_.py in <module>
     19 from scipy.sparse import csgraph
     20 
---> 21 from ._hdbscan_linkage import (single_linkage,
     22                                mst_linkage_core,
     23                                mst_linkage_core_vector,

hdbscan/_hdbscan_linkage.pyx in init hdbscan._hdbscan_linkage()

AttributeError: type object 'hdbscan._hdbscan_linkage.UnionFind' has no attribute '__reduce_cython__'
```

```
nosetests -s hdbscan
============================================================================
ERROR: Failure: ModuleNotFoundError (No model named 'hdbscan._hdbscan_linkage')
----------------------------------------------------------------------------
Traceback (most recent call last):
...
...
ModuleNotFoundError: No model named 'hdbscan._hdbscan_linkage'
```

**Comment by SoumyadeepThakur** [comment]
Seems that the solution to this problem is updating the version of numpy.

`pip install --upgrade --user numpy`
 for pip users

**Comment by Srishti8** [comment]
I tried upgrading the version of numpy too, it still gives me the same error. Windows user, installed through pip

**Comment by lmcinnes** [comment]
If you can install through conda that may help with a lot of issues on windows.

**Comment by LogicPlum** [comment]
Our team is getting an error as well. Our error seems like it may be related to issue [#258](https://github.com/scikit-learn-contrib/hdbscan/issues/258). 

```
Python 3.5.4 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:15:17) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdbscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\hdbscan\__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "D:\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "__init__.pxd", line 918, in init hdbscan._hdbscan_linkage
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by Srishti8** [comment]
To make hdbscan work on my system, I updated scipy, numpy, closed the notebook once, restarted it and then it started working.

**Comment by lmcinnes** [comment]
@LogicPlum That looks like there are som incompatibilities with the numpy version you have installed. It is possible that the windows pip wheels are not working on your platform. If you can install the conda version that would definitely be better, otherwise your next bets alternative it to try installing directly from source to ensure it gets built against the numpy on your system.

**Comment by hovikgas** [comment]
Hi all,

I tried all of the above as well (upgrading scipy, numpy, cython), restarting everything, but still get the same error. I had no problems installing it, but upon importing I get the following error: 

```>>> import hdbscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Hovanes/anaconda3/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/Users/Hovanes/anaconda3/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "__init__.pxd", line 918, in init hdbscan._hdbscan_linkage
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by lmcinnes** [comment]
@hovikgas Any chance you can install from source (e.g directly from a clone of the repository here)? IF so, does that work okay, or are there still issues?

**Comment by hovikgas** [comment]
@lmcinnes I tried doing that, and ran into multiple issues. First, it kept giving a warning about using deprecated Numpy API: 

```
warning: 
      "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API
      NPY_1_7_API_VERSION" [-W#warnings]
```

Then it kept giving errors about incompatible pointers and warnings about code never being executed (here is just a snippet of that):

```
hdbscan/dist_metrics.c:7052:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
            ^
hdbscan/dist_metrics.c:7084:74: warning: incompatible pointer types passing 'struct
      __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
      __pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *' [-Wincompatible-pointer-types]
  ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hdbscan/dist_metrics.c:6887:168: note: passing argument to parameter '__pyx_v_self' here
  ...__pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_D...
                                                           ^
hdbscan/dist_metrics.c:7845:73: warning: incompatible pointer types passing 'struct
      __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
      __pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *' [-Wincompatible-pointer-types]
  ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hdbscan/dist_metrics.c:7764:166: note: passing argument to parameter '__pyx_v_self' here
  ...__pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_DT...
                                                          ^
hdbscan/dist_metrics.c:8493:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;
```
Ultimately it ended up generating 10 warnings, but continued to check the dependencies for scipy, Cython, scikit-learn, and numpy, finishing the installation for hdbscan==0.8.20. 

Now, when I try to import hdbscan, I get the following error: 

```ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'```

**Comment by lmcinnes** [comment]
Okay, something is very broken in all of this, but I am honestly not sure what. Let me look into it a little bit and then try to get back to you.

**Comment by lmcinnes** [comment]
Okay, the warnings are all fine, and I believe your final problem is potentially due to the fact that python searches the current directory prior to going to look in site-packages. If you finished the install and then ran python from that directory it will find the hdbscan directory sitting there and fail. If you change to another directory *before* running python hopefully it will load the module successfully? That was certainly the case for me.

**Comment by hovikgas** [comment]
Ah, yes, then we just go back to my original error regarding the Numpy.ufunc size changing: 

`ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`

**Comment by lmcinnes** [comment]
Hmm. Unfortunately that is something I can't seem to reproduce. I'm not really much of an expert on numpy and the binary packaging thereof, so we are wandering well outside my expertise at this point. Sorry.

**Comment by VladKha** [comment]
Had this issue several times in jupyter environment right after installation
Restarting the notebook (the one using hdbscan) solved the issue

**Comment by hovikgas** [comment]
I tried restarting several times, to no avail. However, I recently had issues with theano and PyMC3 as well, and, following the advice of various StackOverflow users, I was finally able to fix those issues (which were apparently MacOS Mojave-related). Fortunately, that seems to have fixed my HDBSCAN issues as well! Regardless, thanks for your help @lmcinnes!

**Comment by shangwen777** [comment]
I have the similar issue. 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/19768560/57735815-823b1880-766b-11e9-9a88-17a9e922bbd7.png">

When I try to do pip install hdbscan in terminal, I have this error:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/19768560/57735861-a1d24100-766b-11e9-815d-ab0c37edb91c.png">

**Comment by hovikgas** [comment]
@shangwen777 try installing it through conda-forge:

`conda install -c conda-forge hdbscan`

**Comment by mohitaggarwal1322** [comment]
Hey, has anyone faced issue because of mismatch in the library name? The import hdbscan statement is trying to load a function from _**sklearn.externals.joblib.parallel**_, whereas the actual library name is Parallel, with a capital P. Not sure if this is the reason. TIA!
![Screenshot 2019-06-17 at 5 41 21 PM](https://user-images.githubusercontent.com/51914083/59603507-36c2d100-9127-11e9-814c-36e50c061dd3.png)

**Comment by miretchin** [comment]
@hovikgas 

After installing with

`conda install -c conda-forge hdbscan`

I get the error `ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'` which seems to be an on-and-off error based on previous issues. I've tried updating `numpy` and `scipy`. I'm convinced it has nothing to do with the directory I'm in. I've also checked that the `.so` dependency files are not empty.

I would greatly appreciate any advice! Thank you!

**Comment by hovikgas** [comment]
@miretchin Yeah, check the version compatibility. Your numpy and scipy might be TOO new, so you might have to downgrade them to the latest compatible version.

**Comment by Mashfiq137** [comment]
Hi,

I had the same error and it was fixed when I updated my pip:

`pip install --upgrade pip`


Then tried to install it again:

`pip install hdbscan`


 and restarted the notebook.

**Comment by pulkit23** [comment]
O

**Comment by pulkit23** [comment]
Hi guys,

I tried many of the steps suggested here and at other places but to no avail. org. 
However, I realized that hdbscan is working with some specific versions of packages and is failing otherwise. Following is the list of versions that made it finally import for me:

hdbscan=0.8.19=py37h3010b51_0
matplotlib=3.2.2=0
numpy=1.15.4=py37h7e9f1db_0
pandas=0.23.4=py37h04863e7_0
scikit-learn=0.20.1=py37hd81dba3_0
scipy=1.1.0=py37h7c811a0_2
tensorflow=1.13.1=mkl_py37h54b294f_0

I have also attached my conda environment file here.
[hdbscan.txt](https://github.com/scikit-learn-contrib/hdbscan/files/4944412/hdbscan.txt)

**Comment by lahalan** [comment]
> @lmcinnes我尝试这样做，但遇到了多个问题。首先，它不断发出关于使用已弃用的 Numpy API 的警告：
> 
> ```
> warning: 
>       "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API
>       NPY_1_7_API_VERSION" [-W#warnings]
> ```
> 
> 然后它不断给出关于不兼容指针的错误和关于永远不会执行的代码的警告（这里只是其中的一个片段）：
> 
> ```
> hdbscan/dist_metrics.c:7052:13: warning: code will never be executed [-Wunreachable-code]
>   __pyx_r = 0;
>             ^
> hdbscan/dist_metrics.c:7084:74: warning: incompatible pointer types passing 'struct
>       __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
>       __pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *' [-Wincompatible-pointer-types]
>   ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> hdbscan/dist_metrics.c:6887:168: note: passing argument to parameter '__pyx_v_self' here
>   ...__pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_D...
>                                                            ^
> hdbscan/dist_metrics.c:7845:73: warning: incompatible pointer types passing 'struct
>       __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
>       __pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *' [-Wincompatible-pointer-types]
>   ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> hdbscan/dist_metrics.c:7764:166: note: passing argument to parameter '__pyx_v_self' here
>   ...__pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_DT...
>                                                           ^
> hdbscan/dist_metrics.c:8493:13: warning: code will never be executed [-Wunreachable-code]
>   __pyx_r = 0;
> ```
> 
> 最终它最终生成了 10 个警告，但继续检查 scipy、Cython、scikit-learn 和 numpy 的依赖关系，完成 hdbscan==0.8.20 的安装。
> 
> 现在，当我尝试导入 hdbscan 时，出现以下错误：
> 
> `ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'`


报错的原因是i：作者在hdbcan文件夹下面没有给出真正的源码，而给的是.pyx
进入hdbscan文件夹
easycython *.pyx，会生成对应的.pyd文件
运行example中的例子就可以了

**Comment by lahalan** [comment]
hdbsan使用报错_hdbscan_linkage问题解决
ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'


报错的原因是i：作者在hdbcan文件夹下面没有给出真正的源码，而给的是.pyx
进入hdbscan文件夹
easycython *.pyx，会生成对应的.pyd文件
运行example中的例子就可以了

anaconda环境参考
name: python36-hdbscan
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py36haa95532_0
  - cycler=0.10.0=py36haa95532_0
  - cython=0.26.1=py36h18049ac_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2021.3.0=haa95532_3372
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.1=py36hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - matplotlib=2.2.3=py36hd159220_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2018.0.3=1
  - numpy=1.12.1=py36hf30b8aa_1
  - openssl=1.0.2t=vc14h62dcd97_0
  - pip=21.0.1=py36haa95532_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h6538335_2
  - python=3.6.13=h3758d61_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.6=vc14h1e9a669_2
  - scikit-learn=0.19.0=py36h294a771_2
  - scipy=1.0.0=py36h1260518_0
  - setuptools=52.0.0=py36haa95532_0
  - sip=4.19.8=py36h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2021.3.0=h59b6b97_0
  - tbb4py=2021.3.0=py36h59b6b97_0
  - tornado=6.1=py36h2bbff1b_0
  - traitlets=4.3.3=py36_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py36h7fe50ca_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - begins==0.9
    - easycython==1.0.7
prefix: D:\ProgramData\Anaconda3\envs\python36-hdbscan

**Comment by lahalan** [comment]
**_ hdbscan_ Linkage problem:Solved**
`ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'
`
Reasons for error reporting:
The author did not 

- give the real source code under the hdbcan folder, but gave. Pyx

Solution:

- Enter hdbscan folder
-` Easycython *. Pyx `will generate the corresponding. PYD file
- Just run the example in example

**Comment by allanckw** [comment]
> > @lmcinnes我尝试这样做，但遇到了多个问题。首先，它不断发出关于使用已弃用的 Numpy API 的警告：
> > ```
> > warning: 
> >       "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API
> >       NPY_1_7_API_VERSION" [-W#warnings]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后它不断给出关于不兼容指针的错误和关于永远不会执行的代码的警告（这里只是其中的一个片段）：
> > ```
> > hdbscan/dist_metrics.c:7052:13: warning: code will never be executed [-Wunreachable-code]
> >   __pyx_r = 0;
> >             ^
> > hdbscan/dist_metrics.c:7084:74: warning: incompatible pointer types passing 'struct
> >       __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
> >       __pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *' [-Wincompatible-pointer-types]
> >   ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
> >      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > hdbscan/dist_metrics.c:6887:168: note: passing argument to parameter '__pyx_v_self' here
> >   ...__pyx_obj_7hdbscan_12dist_metrics_SEuclideanDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_D...
> >                                                            ^
> > hdbscan/dist_metrics.c:7845:73: warning: incompatible pointer types passing 'struct
> >       __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *' to parameter of type 'struct
> >       __pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *' [-Wincompatible-pointer-types]
> >   ...((struct __pyx_obj_7hdbscan_12dist_metrics_DistanceMetric *)__pyx_v_self), __pyx_v_x1, __pyx_v_x2, __...
> >      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > hdbscan/dist_metrics.c:7764:166: note: passing argument to parameter '__pyx_v_self' here
> >   ...__pyx_obj_7hdbscan_12dist_metrics_MinkowskiDistance *__pyx_v_self, __pyx_t_7hdbscan_12dist_metrics_DT...
> >                                                           ^
> > hdbscan/dist_metrics.c:8493:13: warning: code will never be executed [-Wunreachable-code]
> >   __pyx_r = 0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最终它最终生成了 10 个警告，但继续检查 scipy、Cython、scikit-learn 和 numpy 的依赖关系，完成 hdbscan==0.8.20 的安装。
> > 现在，当我尝试导入 hdbscan 时，出现以下错误：
> > `ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'`
> 
> 报错的原因是i：作者在hdbcan文件夹下面没有给出真正的源码，而给的是.pyx 进入hdbscan文件夹 easycython *.pyx，会生成对应的.pyd文件 运行example中的例子就可以了


哇靠!你救了我一命, 你是怎么发现的

作者直到今天 还是没有解决
