### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by ixxie** [scikit-learn-contrib/hdbscan#272]
Not entirely sure HDBSCAN is at fault here (maybe we broke something in our environment), but the latest build of our container exhibited the following error, which seems to trace into HDBSCAN:

```
File "/myfile.py", line 32, in <module>
     import hdbscan
   File "/usr/local/lib/python3.6/site-packages/hdbscan/__init__.py", line 1, in <module>
     from .hdbscan_ import HDBSCAN, hdbscan
   File "/usr/local/lib/python3.6/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
     from ._hdbscan_linkage import (single_linkage,
   File "__init__.pxd", line 918, in init hdbscan._hdbscan_linkage
 ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

Any clues?

**Comment by ll-DS** [comment]
Import error  "from pmdarima.arima import auto_arima"
anaconda 3.7   numpy version=1.15.4

**Comment by hovikgas** [comment]
I have numpy 1.16.2 and I still get the error. I installed it fine through command line using pip, but upon importing it in JupyterLab, I get the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-2-3f5a460d7435> in <module>
----> 1 import hdbscan

~/anaconda3/lib/python3.7/site-packages/hdbscan/__init__.py in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import approximate_predict, membership_vector, all_points_membership_vectors
      5 

~/anaconda3/lib/python3.7/site-packages/hdbscan/hdbscan_.py in <module>
     19 from scipy.sparse import csgraph
     20 
---> 21 from ._hdbscan_linkage import (single_linkage,
     22                                mst_linkage_core,
     23                                mst_linkage_core_vector,

__init__.pxd in init hdbscan._hdbscan_linkage()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by odbarragan** [comment]
@hovikgas upgrading for me to 1.16.1 finally fixed it!

pip install numpy==1.16.1

**Comment by hovikgas** [comment]
@odbarragan I'm already on 1.16.2... so I should dowgrade to 1.16.1?

**Comment by odbarragan** [comment]
@hovikgas Yes downgrading to 1.16.1 worked for me so that may work for you as well. You might have to do pip uninstall numpy until there are no versions of numpy left and then do pip install numpy==1.16.1.

**Comment by ben-albrecht** [comment]
For anyone else looking, I believe this is the numpy issue on this problem: https://github.com/numpy/numpy/issues/12785

**Comment by digulla** [comment]
I'm seeing 7 of those warnings when creating docs using Sphinx.
I get the warning for the following numpy versions:
1.16.0, 1.16.1, 1.16.2, 1.16.3 and 1.16.4
I don't get the warning for:
1.15.1, 1.15.3, 1.15.4

I'm on Ubuntu 18.04.2 LTS and I've installed numpy using `pip install numpy==...`

**Comment by jinliangXX** [comment]
Error when I used version 1.16.3, downgrading to 1.16.0 addresses this issue
’‘’conda install numpy=1.16.0'''

**Comment by anerisheth19** [comment]
This error needs to be solved the following way:

1) Check your numpy version first using python -c "import numpy; print(numpy.__version__)"
2) If it is higher than 1.16.0, uninstall numpy using sudo pip uninstall numpy
3) Reinstall numpy using pip along with specifying version using sudo pip install numpy==1.16.1

This solved my problem.

**Comment by serbinsh** [comment]
I also solved this issue by installing ```numpy==1.16.1```

**Comment by EngineTai** [comment]
It doesn’t work☹
Pls check the log for detail, any suggestion is welcomed!

________________________________
发件人: Shawn P. Serbin <notifications@github.com>
发送时间: Tuesday, September 24, 2019 1:59:16 AM
收件人: scikit-learn-contrib/hdbscan <hdbscan@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [scikit-learn-contrib/hdbscan] ValueError: numpy.ufunc size changed, may indicate binary incompatibility (#272)


I also solved this issue by installing numpy==1.16.1

**Comment by Jyothif** [comment]
(https://user-images.githubusercontent.com/49805964/73639197-e4bcc480-4691-11ea-843f-3bf708bce66c.PNG)

**Comment by eustomaqua** [comment]
> This error needs to be solved the following way:
> 
> 1. Check your numpy version first using python -c "import numpy; print(numpy.**version**)"
> 2. If it is higher than 1.16.0, uninstall numpy using sudo pip uninstall numpy
> 3. Reinstall numpy using pip along with specifying version using sudo pip install numpy==1.16.1
> 
> This solved my problem.

I attempted to use "pip install numpy==1.16.1" (or 1.16.4, 1.16.5, 1.16.0), none of them worked.
Could you please tell me more about which part in numpy will raise this warning? Thanks

**Comment by LangeJustin** [comment]
If you are working on a **jupyter notebook**, you might want to additionally restart your kernel.

1. pip install numpy==1.16.1
2. Restart Kernel

**Comment by mamunctg** [comment]
upgrade 
pip install numpy==1.16.1

**Comment by Ravikumar-Pawar** [comment]
yes, uninstall the existing NumPy and install a higher version i.e latest version of NumPy can solve this issue
*pip uninstall numpy --user
*pip install numpy==1.16.1
