### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by erinboyle** [scikit-learn-contrib/hdbscan#281]
Hi, I just tried installing hdbscan for the first time with pip. Reporting a failure from `nosetests -s hdbscan`:

```
E
======================================================================
ERROR: Failure: ValueError (numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/py3env/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/py3env/lib/python3.6/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/py3env/lib/python3.6/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/py3env/lib/python3.6/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/py3env/lib/python3.6/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "__init__.pxd", line 918, in init hdbscan._hdbscan_linkage
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

**Comment by erinboyle** [comment]
I just found [this](https://github.com/scikit-learn-contrib/hdbscan/issues/272), but only after I had rolled back the install, so I didn't manually bump numpy. Looks like my numpy was 1.15.4 and probably didn't get upgraded with the hdb install?

I installed into a clean virtualenv and the tests failed again. 
```................SSS.SS......F........E.F
======================================================================
ERROR: hdbscan.tests.test_rsl.test_rsl_high_dimensional
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/hdbscan/tests/test_rsl.py", line 131, in test_rsl_high_dimensional
    V=np.ones(H.shape[1])).fit(H).labels_
TypeError: __init__() got an unexpected keyword argument 'V'

======================================================================
FAIL: hdbscan.tests.test_hdbscan.test_hdbscan_is_sklearn_estimator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/hdbscan/tests/test_hdbscan.py", line 574, in test_hdbscan_is_sklearn_estimator
    check_estimator(HDBSCAN)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py", line 296, in check_estimator
    check_no_attributes_set_in_init(name, estimator)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/sklearn/utils/testing.py", line 348, in wrapper
    return fn(*args, **kwargs)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py", line 1996, in check_no_attributes_set_in_init
    % (name, sorted(invalid_attr)))
AssertionError: {'_single_linkage_tree', '_relative_validity', '_outlier_scores', '_condensed_tree', '_min_spanning_tree', '_raw_data', '_metric_kwargs', '_prediction_data'} is not false : Estimator HDBSCAN should not set any attribute apart from parameters during init. Found attributes ['_condensed_tree', '_metric_kwargs', '_min_spanning_tree', '_outlier_scores', '_prediction_data', '_raw_data', '_relative_validity', '_single_linkage_tree'].

======================================================================
FAIL: hdbscan.tests.test_rsl.test_rsl_is_sklearn_estimator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/hdbscan/tests/test_rsl.py", line 202, in test_rsl_is_sklearn_estimator
    check_estimator(RobustSingleLinkage)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py", line 295, in check_estimator
    check_parameters_default_constructible(name, Estimator)
  File "/Users/erinboyle/.pyenv/versions/3.6.7/envs/hdb/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py", line 2121, in check_parameters_default_constructible
    np.float64, types.FunctionType, Memory])
AssertionError: <class 'dict'> not found in [<class 'str'>, <class 'int'>, <class 'float'>, <class 'bool'>, <class 'tuple'>, <class 'NoneType'>, <class 'numpy.float64'>, <class 'function'>, <class 'sklearn.externals.joblib.memory.Memory'>]

----------------------------------------------------------------------
Ran 40 tests in 2.827s

FAILED (SKIP=5, errors=1, failures=2)```

**Comment by lmcinnes** [comment]
You can safely ignore those test failures. They make use of functionality in sklearn to verify that the classes meet compatibility standards for sklearn models. The most recent releases of sklearn strengthened the requirements and I haven't yet had the time to go through and make the requisite changes to hdbscan. In general everything works, there are just some quirks about how certain things are handled in terms of parameters that do not meet the newer way that sklearn expects things to be done.
