### ISSUE TITLE
Hdbscan Install Numpy.unfunc Issue 

### ISSUE THREAD

**Issue by Ghoworth** [scikit-learn-contrib/hdbscan#288]
Ran test for HDBSCAN and here is the error log (see below) -  

Have pip installed from  github, pip installed HDBSCAN and still same error - Tried everything in various posts on github and stackflow , but still same error

Seems like an incompatibility of Numpy with HDBSCAN - using latest Numpy and all packages are up to date.  Running python 3.6

C:\WINDOWS\system32>python -m nose -s hdbscan
C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
E
======================================================================
ERROR: Failure: ValueError (numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\nose\loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\hdbscan\__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "C:\Users\wjb17117\AppData\Local\Programs\Python\Python36\lib\site-packages\hdbscan\hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "__init__.pxd", line 918, in init hdbscan._hdbscan_linkage
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

C:\WINDOWS\system32>

**Comment by lmcinnes** [comment]
Sadly I think this is an issue with the wheel builds for windows which I technically manage, but have little real knowledge of ability to fix (someone else very kindly set up the process for me, and I admit to having little understanding of the fine-points therein). The best approach is to use the conda-forge build, which I know works, but that requires you to use conda to install stuff ratrher than pip, and that may be an issue for you.
