### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_clusters'

### ISSUE THREAD

**Issue by kapkirl** [scikit-learn-contrib/hdbscan#30]
Hi,
I was trying to run code with robust single linkage. Here is example.

```
import numpy as np
import sklearn.datasets as data
import hdbscan

ss = 100
moons, _ = data.make_moons( n_samples = ss, noise = 0.05 )
blobs, _ = data.make_blobs(
    n_samples = ss,
    centers=[( -0.75, 2.25 ), ( 1.0, 2.0 )],
    cluster_std = 0.25
)

test_data = np.vstack([moons, blobs])

clusterer = hdbscan.RobustSingleLinkage(cut=0.125, k=7)
cluster_labels = clusterer.fit_predict( test_data )
hierarchy = clusterer.cluster_hierarchy_
alt_labels = hierarchy.get_clusters(0.100, 5)
hierarchy.plot()
```

But received such warning and error message:

/usr/local/lib/python2.7/dist-packages/hdbscan/robust_single_linkage_.py:395: UserWarning: No single linkage tree was generated; try running fit first.
  warn('No single linkage tree was generated; try running fit first.')
Traceback (most recent call last):
  File "test_robustsinglelinkage.py", line 21, in <module>
    alt_labels = hierarchy.get_clusters(0.100, 5)
AttributeError: 'NoneType' object has no attribute 'get_clusters'

I'm not sure, but it seems that problem is in this line of code in file robust_single_linkage.py:
`self.labels_, self._cluster_hierarchy = robust_single_linkage(X, **self.get_params())`

but should be:
`self.labels_, self._cluster_hierarchy_ = robust_single_linkage(X, **self.get_params())`

**Comment by lmcinnes** [comment]
Good call. That is exactly the problem. I'll fix that now. Hopefully you can fix it for yourself as well and have everything working. Thanks for the fix!

**Comment by kapkirl** [comment]
After fixing this problem I faced with another. Sample code is the same as in the beginning. 
While executing this line:
`alt_labels = hierarchy.get_clusters(0.100, 5)`

resulting to this error:
alt_labels = hierarchy.get_clusters(0.100, 5)
  File ".../hdbscan/plots.py", line 588, in get_clusters
    return labelling_at_cut(self._linkage, cut_distance, min_cluster_size)
TypeError: Argument 'linkage' has incorrect type (expected numpy.ndarray, got SingleLinkageTree)

Here is how I fixed it. In "robust_single_linkage.py"

```
@property
    def cluster_hierarchy_(self):
        if self._cluster_hierarchy_ is not None:
            #return SingleLinkageTree(self._cluster_hierarchy_) <- was
            return self._cluster_hierarchy_   # <- fixed
        else:
            warn('No single linkage tree was generated; try running fit first.')
            return None
```

As I understand SingleLinkageTree needs as parameters linkage in form numpy array, but recieved the whole tree. So when in further code we tries to access linkage, we received the whole tree. And that is bad. 

Maybe I missed something, but now it works :).

**Comment by jc-healy** [comment]
Sounds good.  We're out of the country at the moment with limited
Internet.  We'll fix this as soon as we get back.  Thank you so much for
the fix.  We really appreciate you stepping up.

Cheers
John

**Comment by ompatri** [comment]
I got the same error today
`TypeError: Argument 'linkage' has incorrect type (expected numpy.ndarray, got SingleLinkageTree)`
Has this been fixed ?

**Comment by lmcinnes** [comment]
I thought it to be fixed, but perhaps there has been a regression. I'll try to look at it soon.

**Comment by AbhishekHP2016** [comment]
import hdbscan
from sklearn.datasets import make_blobs
data = make_blobs(1000)

replace the above line with below
data,labels = make_blobs(1000)

else
ValueError: could not broadcast input array from shape (1000,2) into shape (1000)

**Comment by ShaharKatz** [comment]
Original problem persists after changing to `data = make_blobs(1000)`, any update?

**Comment by lmcinnes** [comment]
I have unfortunately been very busy on other projects lately, and haven't had time to look at this. I would certainly be happy to vet a pull request if that's possible.
