### ISSUE TITLE
Memory increase causes Memory Error to happen earlier

### ISSUE THREAD

**Issue by fabiannagel** [scikit-learn-contrib/hdbscan#300]
I ran HDBSCAN on my local Mac machine with 16 GB of memory on 25% of my dataset, which is 1.000.000 data points. After a while, the system usually gets unresponsive. Eventually, the script is killed by the kernel.

Hence, I moved everything to an Azure VM with 4 cores and 64 GB of memory. I tried clustering the same 1.000.000 data points, but now it seems like the script itself runs into memory issues even earlier than on my local machine.

This is the stacktrace I keep getting:

`Traceback (most recent call last):
  File "HDBSCAN.py", line 31, in <module>
    clusterer.fit(clusteringData)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 893, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 612, in hdbscan
    core_dist_n_jobs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 308, in _hdbscan_boruvka_balltree
    n_jobs=core_dist_n_jobs, **kwargs)
  File "hdbscan/_hdbscan_boruvka.pyx", line 976, in hdbscan._hdbscan_boruvka.BallTreeBoruvkaAlgorithm.__init__
  File "hdbscan/dist_metrics.pyx", line 398, in hdbscan.dist_metrics.DistanceMetric.pairwise
MemoryError`

I'm actually using the haversine metric together with longitude and latitude values (converted to radians) so that's why the last line of the stacktrace is confusing me.

I also lowered the sample count to 500.000 which causes a different stacktrace altogether:

`Traceback (most recent call last):
  File "HDBSCAN.py", line 31, in <module>
    clusterer.fit(clusteringData)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 893, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 612, in hdbscan
    core_dist_n_jobs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 308, in _hdbscan_boruvka_balltree
    n_jobs=core_dist_n_jobs, **kwargs)
  File "hdbscan/_hdbscan_boruvka.pyx", line 984, in hdbscan._hdbscan_boruvka.BallTreeBoruvkaAlgorithm.__init__
  File "hdbscan/_hdbscan_boruvka.pyx", line 1015, in hdbscan._hdbscan_boruvka.BallTreeBoruvkaAlgorithm._compute_bounds
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 874, in __call__
    n_jobs = self._initialize_backend()
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 673, in _initialize_backend
    **self._backend_args)
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 476, in configure
    **memmappingexecutor_args)
  File "/usr/local/lib/python3.7/site-packages/joblib/executor.py", line 36, in get_memmapping_executor
    initargs=initargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 108, in get_reusable_executor
    executor_id=executor_id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 144, in __init__
    initializer=initializer, initargs=initargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 910, in __init__
    self._processes_management_lock = self._context.Lock()
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/context.py", line 225, in Lock
    return Lock()
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 174, in __init__
    super(Lock, self).__init__(SEMAPHORE, 1, 1)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 90, in __init__
    semaphore_tracker.register(self._semlock.name)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 120, in register
    self.ensure_running()
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 99, in ensure_running
    pid = spawnv_passfds(exe, args, fds_to_pass)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 235, in spawnv_passfds
    return fork_exec(args, _pass)
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/backend/fork_exec.py", line 38, in fork_exec
    pid = os.fork()
OSError: [Errno 12] Cannot allocate memory`

Has somebody encountered issues like these? I built Python 3.7 myself on Debian, maybe I missed something there?

Thanks for your help.

**Comment by fabiannagel** [comment]
Also, I keep getting deprecation warnings that I haven't been receiving on my local machine.

```
/usr/local/lib/python3.7/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
```

**Comment by ZagHe568** [comment]
Same issue here. Wonder if you solved it?

**Comment by fabiannagel** [comment]
I don't think so. If I remember correctly, more thorough preprocessing helped me to reduce the dataset size until manageable.
