### ISSUE TITLE
Nosetest fail after building -- Failure: ModuleNotFoundError (No module named 'hdbscan._hdbscan_linkage')

### ISSUE THREAD

**Issue by EngineTai** [scikit-learn-contrib/hdbscan#325]
I cloned this project with Git and built it with the command 'python setup.py install', following the guide in Readme.rst, i run the nosetests, but it reported above ERROR!

Below is the details:
(baseClone) PS E:\github\hdbscan> conda list hdbscan
# packages in environment at C:\Users\ljtnz\Anaconda3\envs\baseClone:
#
# Name                    Version                   Build  Channel
hdbscan                   0.8.22                   pypi_0    pypi
(baseClone) PS E:\github\hdbscan> nosetests -v hdbscan
Failure: ModuleNotFoundError (No module named 'hdbscan._hdbscan_linkage') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'hdbscan._hdbscan_linkage')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\ljtnz\Anaconda3\envs\baseClone\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\github\hdbscan\hdbscan\__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "E:\github\hdbscan\hdbscan\hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
ModuleNotFoundError: No module named 'hdbscan._hdbscan_linkage'

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (errors=1)
(baseClone) PS E:\github\hdbscan>

**Comment by onofricamila** [comment]
The same happened to me while trying to run the validation script. All I had to do in `hdbscan/validity.py` was:

```python
import pyximport
pyximport.install()
from ._hdbscan_linkage import mst_linkage_core
```
Worked like charm (although my IDE still underlines the import statement with red).

Consider that pyximport comes with the cython package.

Cheers!

**Comment by markopy** [comment]
This error happens when running nose test from the hdbscan source folder. Nose imports and tests the currently installed module, not the code in the source folder. You need to run the tests from another folder.
