### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by r0f1** [scikit-learn-contrib/hdbscan#327]
I get the following error message, when I try installing the package:

```
  ERROR: Command errored out with exit status 1: 
command: /projects/anaconda3/bin/python /projects/anaconda3/lib/
python3.7/site-packages/pip install --ignore-installed --no-user --prefix /
tmp/pip-build-env-93se382n/overlay --no-warn-script-location --no-binary 
:none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
cython numpy cwd: None                                               

Complete output (14 lines):
Traceback (most recent call last):                                         
File "/projects/anaconda3/lib/python3.7/runpy.py", line 193, in
 _run_module_as_main "__main__", mod_spec) 
 File "/projects/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) 
 File "/projects/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module> from pip._internal import main as _main  # isort:skip #noqa                                                          
 File "/projects/anaconda3/lib/python3.7/site-packages/pip/_internal/__init__.py", line 4, in <module>                     import locale 
 File "/projects/anaconda3/lib/python3.7/locale.py", line 16, in <module> import re 
 File "/projects/anaconda3/lib/python3.7/re.py", line 143, in <module> class RegexFlag(enum.IntFlag): AttributeError: module 'enum' has no attribute 'IntFlag'
  ---------------------------------------- ERROR: Command errored out with
  exit status 1: /projects/anaconda3/bin/python /projects/anaconda3/lib/
  python3.7/site-packages/pip install --ignore-installed --no-user 
  --prefix /tmp/pip-build-env-93se382n/overlay --no-warn-script-location
   --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 
   setuptools wheel cython numpy Check the logs for full command output.

```

**Comment by lmcinnes** [comment]
That is a very odd error -- it looks like something is messing up internally within pip rather than hdbscan specifically. Have you tried conda installing?

```
conda install -c conda-forge hdbscan
```

**Comment by r0f1** [comment]
Ok thanks that worked! :)

**Comment by vahdat-ab** [comment]
I have the same issue when I try to install hdbscan. I run it inside a docker. Do you exactly why this happens?
