### ISSUE TITLE
Installation fails on Ubuntu

### ISSUE THREAD

**Issue by vishalmhjn** [scikit-learn-contrib/hdbscan#344]
Python 3.6 (with virtualenv)
Ubuntu 18

`pip install hdbscan` fails with the following output:

` ERROR: Command errored out with exit status 1:
   command: /home/vishal/vpython/bin/python3 /home/user/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbfxnv7v6
       cwd: /tmp/pip-install-y7suqwy2/hdbscan
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/user/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/user/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/user/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/user/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/vishal/vpython/bin/python3 /home/vishal/vpython/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbfxnv7v6 Check the logs for full command output.
`

Thanks

**Comment by vishalmhjn** [comment]
Updating to python3.7 helped.

**Comment by reneeburton** [comment]
installation also fails for me on AWS EMR with the same error.   I found this bug issue which indicates a pip and setup tools issue where the package doesn't have 

> The package you are installing does not specify build-backend="setuptools.build_meta" in its pyproject.tom

wondering if we can confirm or otherwise identify fix? 

https://github.com/pypa/setuptools/issues/1694

l.

**Comment by vishalmhjn** [comment]
Does update to python3.7 help in your case?
