### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by MichaelMonashev** [scikit-learn-contrib/hdbscan#376]
Code:
```
    clusterer = hdbscan.HDBSCAN(
        core_dist_n_jobs=os.cpu_count(),
        min_cluster_size = 2000,
    )
    clusterer.fit(embedding)
```
`embedding` has shape (314496, 20).

Error:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 344, in _sendback_result
    exception=exception))
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 240, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cluster_images.py", line 158, in <module>
    _main(parser.parse_args())
  File "cluster_images.py", line 115, in _main
    clusterer.fit(embedding)
  File "/home/xxx/.local/lib/python3.6/site-packages/hdbscan/hdbscan_.py", line 919, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/hdbscan/hdbscan_.py", line 615, in hdbscan
    core_dist_n_jobs, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/hdbscan/hdbscan_.py", line 278, in _hdbscan_boruvka_kdtree
    n_jobs=core_dist_n_jobs, **kwargs)
  File "hdbscan/_hdbscan_boruvka.pyx", line 375, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__
  File "hdbscan/_hdbscan_boruvka.pyx", line 411, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/xxx/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by lmcinnes** [comment]
The catch here, I suspect, is that the number of neighbors being computed is very large and that is pushing things past the limits. You can potentially get around this by explicitly setting ``min_samples`` to something, since if it is not specified it defaults to the value of ``min_cluster_size``. Something like:

```python
    clusterer = hdbscan.HDBSCAN(
        core_dist_n_jobs=os.cpu_count(),
        min_cluster_size = 2000,
        min_samples=100,
    )
    clusterer.fit(embedding)
```
will hopefully work better.

**Comment by MichaelMonashev** [comment]
Thank you! It works!
