### ISSUE TITLE
Test test_hdbscan_boruvka_balltree_matches intermittently fails

### ISSUE THREAD

**Issue by markopy** [scikit-learn-contrib/hdbscan#421]
I saw this test fail only once. Perhaps the check should be less than or equal?

```
FAIL: hdbscan.tests.test_hdbscan.test_hdbscan_boruvka_balltree_matches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "hdbscan/tests/test_hdbscan.py", line 356, in test_hdbscan_boruvka_balltree_matches
    assert_less(num_mismatches / float(data.shape[0]), 0.15)
AssertionError: 0.15 not less than 0.15
```

**Comment by markopy** [comment]
Actually, got the same failure again with different numbers:

```
======================================================================
FAIL: hdbscan.tests.test_hdbscan.test_hdbscan_boruvka_balltree_matches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "hdbscan/tests/test_hdbscan.py", line 356, in test_hdbscan_boruvka_balltree_matches
    assert_less(num_mismatches / float(data.shape[0]), 0.15)
AssertionError: 0.15333333333333332 not less than 0.15
```
