### ISSUE TITLE
Error message when printing relative validity score

### ISSUE THREAD

**Issue by ivan-marroquin** [scikit-learn-contrib/hdbscan#478]
Hi,

Many thanks for this great package!

I am using Python 3.6.5 with hdbscan 0.8.27. The clustering model is generated as follows:

clustering= hdbscan.HDBSCAN(min_cluster_size= 60, min_samples= 10, metric= 'minkowski', p= 0.1, alpha= 1.0, 
                                                   cluster_selection_epsilon= 1.0, algorithm= 'prims_kdtree', core_dist_n_jobs= 
                                                   cpu_count, cluster_selection_method= 'eom', memory= working_dir, 
                                                   gen_min_span_tree= True)

After the model is fitted to data to be clustered. I would like to print the relative validity score. This is when, I get this error message

Traceback (most recent call last):
  File "test_hdbscan_clustering.py", line 101, in <module>
    print('Relative quality of clustering output ', clustering.relative_validity_)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\hdbscan\hdbscan_.py", line 1132, in relative_validity_
    mst_df = self.minimum_spanning_tree_.to_pandas()
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\hdbscan\hdbscan_.py", line 1086, in minimum_spanning_tree_
    raise AttributeError('No minimum spanning tree was generated.'
AttributeError: No minimum spanning tree was generated.This may be due to optimized algorithm variations that skip explicit generation of the spanning tree.

Any suggestions,

Ivan

**Comment by chaturv3di** [comment]
Not sure if this is still relevant, but this is a behavior I couldn't quite nail down. HDBSCAN skips the explicit generation of the MST sometimes.

My suggestion would be to try changing hyper-parameters to figure out one where an MST is actually generated. Sorry I cannot be more precise at this time.
