### ISSUE TITLE
[Question] ValueError: unsupported pickle protocol: 5 with Python 3.7.11

### ISSUE THREAD

**Issue by whymauri** [scikit-learn-contrib/hdbscan#538]
Hi all, clustering fails with >20k points of dim 32 with the following HDBSCAN arguments:

```
hdbscan_min_samples = 4
hdscan_min_cluster_size = 56
model = hdbscan.HDBSCAN(
    cluster_selection_method='eom', 
    min_samples=hdbscan_min_samples, 
    min_cluster_size=hdscan_min_cluster_size,
    prediction_data=True
)
```

Where `core_dist_n_jobs` is left at default. It will not fail if I set it to one, but that seems suboptimal. Full stacktrace:

```
--------------------------------------------------------------------------------
LokyProcess-2 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-1 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5


--------------------------------------------------------------------------------
---------------------------------------------------------------------------
TerminatedWorkerError                     Traceback (most recent call last)
<timed exec> in <module>

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/hdbscan/hdbscan_.py in fit_predict(self, X, y)
    939             cluster labels
    940         """
--> 941         self.fit(X)
    942         return self.labels_
    943 

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/hdbscan/hdbscan_.py in fit(self, X, y)
    917          self._condensed_tree,
    918          self._single_linkage_tree,
--> 919          self._min_spanning_tree) = hdbscan(X, **kwargs)
    920 
    921         if self.prediction_data:

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/hdbscan/hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, cluster_selection_epsilon, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    613                                              approx_min_span_tree,
    614                                              gen_min_span_tree,
--> 615                                              core_dist_n_jobs, **kwargs)
    616         else:  # Metric is a valid BallTree metric
    617             # TO DO: Need heuristic to decide when to go to boruvka;

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/hdbscan/hdbscan_.py in _hdbscan_boruvka_kdtree(X, min_samples, alpha, metric, p, leaf_size, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, **kwargs)
    276                                  leaf_size=leaf_size // 3,
    277                                  approx_min_span_tree=approx_min_span_tree,
--> 278                                  n_jobs=core_dist_n_jobs, **kwargs)
    279     min_spanning_tree = alg.spanning_tree()
    280     # Sort edges of the min_spanning_tree by weight

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__()

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds()

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/home/default_user/.conda/envs/user/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/home/default_user/.conda/envs/user/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
```

I am monitoring memory, and it does not look like an OOM. It seems to be an issue with joblib and the loading/dumping protocol. What confuses me is that it's impossible to dump with pickle protocol 5 on Python `3.7.11` in the first place, so I have no clue why it's trying to load from that protocol. All work on this project has been done on `3.7.11`.

Here are the relevant dependency versions:

```
Package                      Version
---------------------------- -------------------------
Cython                       0.29.3
hdbscan                      0.8.27
joblib                       1.1.0
numba                        0.53.1
numpy                        1.21.5
pandas                       1.3.5
pickle5                      0.0.11
scikit-learn                 0.24.2
```

Feel free to let me know if there's any other relevant dependencies. If a downgrade or upgrade of a package could fix this, that'd be awesome!

**Comment by PanayotisManganaris** [comment]
I have the same problem with a RandomForestRegressor in python 3.7.13 after patching with sklearnex.

loky uses it's own serialization tools, the settings of which cause the confusion. I was able to use the following context manager to change the parallelization backend to avoid the issue. It may slow execution slightly. I haven't tried to time it yet.

with joblib.parallel_backend('multiprocessing'): 
    regr.fit(X,y)
