### ISSUE TITLE
Error on Apple M1 Pro with macOS 12 - Incompatible architecture

### ISSUE THREAD

**Issue by leifericf** [scikit-learn-contrib/hdbscan#547]
I'm using the package [BERTopic](https://github.com/MaartenGr/BERTopic), which depends on hdbscan.

When I run the sample application, I get an error. See details below.

System software:

```
System Version: macOS 12.4 (21F79)
Kernel Version: Darwin 21.5.0
```

System hardware:

```
Name: MacBook Pro
Identifier: MacBookPro18,1
Name: Unknown
Speed: 2,4 GHz
Number of Processors: 1
Total Number of Cores: 10
L2 Cache: 20 MB
Memory: 16 GB
```

Error message:

```
$ cd ~/code/my-project ; /usr/bin/env ~/opt/miniconda3/envs/my-project/bin/python ~/.vscode/extensions/ms-python.python-2022.6.3/pythonFiles/lib/python/debugpy/launcher 62735 -- ~/code/my-project/src/nl
p.py 
Traceback (most recent call last):
  File "~/code/my-project/src/nlp.py", line 1, in <module>
    from bertopic import BERTopic
  File "~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/bertopic/__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File "~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/bertopic/_bertopic.py", line 21, in <module>
    import hdbscan
  File "~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 20, in <module>
    from ._hdbscan_linkage import (
ImportError: dlopen(~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan/_hdbscan_linkage.cpython-310-darwin.so, 0x0002): tried: '~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan/_hdbscan_linkage.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Code to reproduce the error:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)

topic_model.get_topic_info()

topic_model.get_topic(0)
```

[`environment.yml` (for Conda)](https://gist.github.com/leifericf/5d92f4b99db64821f9a86d2d4f0b94d4) with Python- and package version info.

**Comment by leifericf** [comment]
This hdbscan sample code produces the exact same error in a fresh conda environment:

```python
import hdbscan
from sklearn.datasets import make_blobs

data, _ = make_blobs(1000)

clusterer = test.HDBSCAN(min_cluster_size=10)
cluster_labels = clusterer.fit_predict(data)
```

**Comment by leifericf** [comment]
Interesting! I got this usage example code working in a new Conda environment:

```python
from sklearn.datasets import make_blobs
import hdbscan
import matplotlib.pyplot as plt

data, _ = make_blobs(1000)

clusterer = hdbscan.RobustSingleLinkage(cut=0.125, k=7)
cluster_labels = clusterer.fit_predict(data)
hierarchy = clusterer.cluster_hierarchy_
alt_labels = hierarchy.get_clusters(0.100, 5)
hierarchy.plot()

plt.show()
```

Conda environment:

```
name: hdbscan-error
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.7=hc377ac9_0
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2022.4.26=hca03da5_0
  - certifi=2022.5.18.1=py310hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - giflib=5.2.1=h1a28f6b_0
  - hdbscan=0.8.28=py310h949c51b_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h1a28f6b_0
  - kiwisolver=1.4.2=py310hc377ac9_0
  - lcms2=2.12=hba8e193_0
  - libblas=3.9.0=15_osxarm64_openblas
  - libcblas=3.9.0=15_osxarm64_openblas
  - libcxx=12.0.0=hf6beb65_1
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=15_osxarm64_openblas
  - libopenblas=0.3.20=openmp_h2209c59_0
  - libpng=1.6.37=hb8d0fd4_0
  - libtiff=4.2.0=h01837e1_1
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libzlib=1.2.12=h90dfc92_0
  - llvm-openmp=14.0.4=hd125106_0
  - lz4-c=1.9.3=hc377ac9_0
  - matplotlib=3.5.1=py310hca03da5_1
  - matplotlib-base=3.5.1=py310hc377ac9_1
  - munkres=1.1.4=py_0
  - ncurses=6.3=h1a28f6b_2
  - numpy=1.22.1=py310h567df17_0
  - openssl=3.0.3=ha287fd2_0
  - packaging=21.3=pyhd3eb1b0_0
  - pillow=9.0.1=py310h4d1bdd5_0
  - pip=21.2.4=py310hca03da5_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.10.4=h14b404e_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - readline=8.1.2=h1a28f6b_1
  - scikit-learn=1.0.2=py310h5f111c3_0
  - scipy=1.7.3=py310h6ecf4ae_0
  - setuptools=61.2.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.3=h1058600_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.1=py310h1a28f6b_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1a28f6b_1
  - zlib=1.2.12=h90dfc92_0
  - zstd=1.5.2=h8574219_0
prefix: /Users/leif/opt/miniconda3/envs/hdbscan-error

```

I'm trying to determine the cause of the error now.

Perhaps I have some incorrect/incompatible packages installed in my other Conda environment.

**Comment by leifericf** [comment]
I found the root cause and managed to fix it.

Below are the steps in case someone else stumbles upon the same problem in the future.

---

The first problem was that I had installed hdbscan via pip in my conda environment. I believe BERTopic installed it like that. Anaconda recommends installing all packages via conda first, _then_ via pip if necessary.

So the first step was to uninstall hdbscan via pip _within_ my conda environment:

```
$ pip uninstall hdbscan
Found existing installation: hdbscan 0.8.28
Uninstalling hdbscan-0.8.28:
  Would remove:
    ~/opt/miniconda3/envs/my-project/dist_metrics.pxd
    ~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan-0.8.28.dist-info/*
    ~/opt/miniconda3/envs/my-project/lib/python3.10/site-packages/hdbscan/*
Proceed (Y/n)? y
  Successfully uninstalled hdbscan-0.8.28
```

And then re-install hdbscan via conda instead:

```
$ conda install -c conda-forge hdbscan
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                        

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - hdbscan -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0',build=*_cpython]

Your python: python==3.10.4=hbdb9e5c_0

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

Whops! No deal, presumably because I had installed a specific version of Python in my Conda environment. It looks like conda cannot replace my Python version with cpython, which hdbscan requires.

So I had to remove Python from my conda environment:

```
$ conda remove python
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: ~/opt/miniconda3/envs/my-project

  removed specs:
    - python


The following packages will be REMOVED:

  appdirs-1.4.4-pyhd3eb1b0_0
  attrs-21.4.0-pyhd3eb1b0_0
  black-19.10b0-py_0
  bottleneck-1.3.4-py310h96f19d2_0
  brotlipy-0.7.0-py310h1a28f6b_1002
  catalogue-2.0.7-py310hca03da5_0
  certifi-2022.5.18.1-py310hca03da5_0
  cffi-1.15.0-py310h22df2f2_1
  charset-normalizer-2.0.4-pyhd3eb1b0_0
  click-8.0.4-py310hca03da5_0
  colorama-0.4.4-pyhd3eb1b0_0
  cryptography-37.0.1-py310h834c97f_0
  cymem-2.0.6-py310hc377ac9_0
  cython-blis-0.7.7-py310h96f19d2_0
  dash-1.19.0-pyhd3eb1b0_0
  dash-core-components-1.3.1-py_0
  dash-html-components-1.0.1-py_0
  dash-renderer-1.1.2-py_0
  dash-table-4.4.1-pyhd3eb1b0_0
  dataclasses-0.8-pyh6d0b6a4_7
  flask-2.0.3-pyhd3eb1b0_0
  flask-compress-1.5.0-py_0
  future-0.18.2-py310hca03da5_1
  idna-3.3-pyhd3eb1b0_0
  itsdangerous-2.0.1-pyhd3eb1b0_0
  jinja2-3.0.3-pyhd3eb1b0_0
  langcodes-3.3.0-pyhd3eb1b0_0
  markupsafe-2.1.1-py310h1a28f6b_0
  murmurhash-1.0.7-py310hc377ac9_0
  mypy_extensions-0.4.3-py310hca03da5_1
  numexpr-2.8.1-py310h5a06f4b_1
  numpy-1.22.3-py310hdb36b11_0
  numpy-base-1.22.3-py310h5e3e9f0_0
  packaging-21.3-pyhd3eb1b0_0
  pandas-1.4.2-py310hc377ac9_0
  pathspec-0.7.0-py_0
  pathy-0.6.1-py310hca03da5_0
  pip-21.2.4-py310hca03da5_0
  plotly-5.6.0-pyhd3eb1b0_0
  preshed-3.0.6-py310hc377ac9_0
  pycparser-2.21-pyhd3eb1b0_0
  pydantic-1.9.0-py310h1a28f6b_1
  pyopenssl-22.0.0-pyhd3eb1b0_0
  pyparsing-3.0.4-pyhd3eb1b0_0
  pysocks-1.7.1-py310hca03da5_0
  python-3.10.4-hbdb9e5c_0
  python-dateutil-2.8.2-pyhd3eb1b0_0
  python-dotenv-0.20.0-pyhd8ed1ab_0
  pytorch-1.13.0.dev20220607-py3.10_0
  pytz-2021.3-pyhd3eb1b0_0
  pyyaml-6.0-py310h1a28f6b_0
  regex-2022.3.15-py310h1a28f6b_0
  requests-2.27.1-pyhd3eb1b0_0
  setuptools-61.2.0-py310hca03da5_0
  shellingham-1.3.1-pyhd3eb1b0_0
  six-1.16.0-pyhd3eb1b0_1
  smart_open-5.2.1-py310hca03da5_0
  spacy-3.3.0-py310h09aeb25_0
  spacy-legacy-3.0.9-py310hca03da5_0
  spacy-loggers-1.0.1-pyhd3eb1b0_0
  srsly-2.4.3-py310hc377ac9_0
  tenacity-8.0.1-py310hca03da5_0
  thinc-8.0.15-py310h09aeb25_0
  toml-0.10.2-pyhd3eb1b0_0
  tqdm-4.64.0-py310hca03da5_0
  typed-ast-1.4.3-py310h1a28f6b_1
  typer-0.4.1-py310hca03da5_0
  typing-extensions-4.1.1-hd3eb1b0_0
  typing_extensions-4.1.1-pyh06a4308_0
  unidecode-1.2.0-pyhd3eb1b0_0
  urllib3-1.26.9-py310hca03da5_0
  wasabi-0.9.1-py310hca03da5_0
  werkzeug-2.0.3-pyhd3eb1b0_0
  wheel-0.37.1-pyhd3eb1b0_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```

 And re-install Python without the specific build version:

```
$ conda install python=3.10.4                   
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: ~/opt/miniconda3/envs/my-project

  added / updated specs:
    - python=3.10.4


The following NEW packages will be INSTALLED:

  certifi            pkgs/main/osx-arm64::certifi-2022.5.18.1-py310hca03da5_0
  pip                pkgs/main/osx-arm64::pip-21.2.4-py310hca03da5_0
  python             pkgs/main/osx-arm64::python-3.10.4-hbdb9e5c_0
  setuptools         pkgs/main/osx-arm64::setuptools-61.2.0-py310hca03da5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

And now we can attempt to install hdbscan via conda again:

```
$ conda install -c conda-forge hdbscan          
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: ~/opt/miniconda3/envs/my-project

  added / updated specs:
    - hdbscan


The following NEW packages will be INSTALLED:

  hdbscan            conda-forge/osx-arm64::hdbscan-0.8.28-py310h949c51b_1
  joblib             conda-forge/noarch::joblib-1.1.0-pyhd8ed1ab_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-15_osxarm64_openblas
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-15_osxarm64_openblas
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-15_osxarm64_openblas
  libzlib            conda-forge/osx-arm64::libzlib-1.2.12-h90dfc92_0
  numpy              conda-forge/osx-arm64::numpy-1.22.1-py310h567df17_0
  python_abi         conda-forge/osx-arm64::python_abi-3.10-2_cp310
  scikit-learn       conda-forge/osx-arm64::scikit-learn-1.0.2-py310h5f111c3_0
  scipy              conda-forge/osx-arm64::scipy-1.7.3-py310h6ecf4ae_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.1.0-pyh8a188c0_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.4.26-~ --> conda-forge::ca-certificates-2022.5.18.1-h4653dfc_0
  openssl              pkgs/main::openssl-1.1.1o-h1a28f6b_0 --> conda-forge::openssl-3.0.3-ha287fd2_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2022.5.18.1-py310h~ --> conda-forge::certifi-2022.5.18.1-py310hbe9552e_0
  python                pkgs/main::python-3.10.4-hbdb9e5c_0 --> conda-forge::python-3.10.4-h14b404e_0_cpython
  zlib                    pkgs/main::zlib-1.2.12-h5a0b063_2 --> conda-forge::zlib-1.2.12-h90dfc92_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Much better! Notice that conda is now able to replace `pkgs/main::python-3.10.4-hbdb9e5c_0` with `conda-forge::python-3.10.4-h14b404e_0_cpython`. And the installation is indeed successful.
