### ISSUE TITLE
error while running hdbscan test

### ISSUE THREAD

**Issue by hbazizi** [scikit-learn-contrib/hdbscan#553]
Hi

I got the below error while running the hdbscan test. is there any significant issues? Appreciate your help.

thank you

PS C:\Users\K19067372\Documents> nosetests -s hdbscan
............................................EE..........E
======================================================================
ERROR: hdbscan.tests.test_hdbscan.test_hdbscan_is_sklearn_estimator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\tests\test_hdbscan.py", line 646, in test_hdbscan_is_sklearn_e
stimator
    check_estimator(HDBSCAN)
  File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\estimator_checks.py", line 567, in check_estimator
    raise TypeError(msg)
TypeError: Passing a class was deprecated in version 0.23 and isn't supported anymore from 0.24.Please pass an instance ins
tead.

======================================================================
ERROR: hdbscan.tests.test_prediction_utils.test_safe_always_positive_division
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_safe_always_positive_division() missing 1 required positional argument: 'denominator'

======================================================================
ERROR: hdbscan.tests.test_rsl.test_rsl_is_sklearn_estimator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\tests\test_rsl.py", line 197, in test_rsl_is_sklearn_estimator

    check_estimator(RobustSingleLinkage)
  File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\estimator_checks.py", line 567, in check_estimator
    raise TypeError(msg)
TypeError: Passing a class was deprecated in version 0.23 and isn't supported anymore from 0.24.Please pass an instance ins
tead.

----------------------------------------------------------------------
Ran 57 tests in 17.313s

FAILED (errors=3)

**Comment by kiranshila** [comment]
I am also getting these errors - any progress on this?

**Comment by kiranshila** [comment]
It looks like because these tests are set as skip in pytest, a directive ignored by other test runners.

**Comment by kiranshila** [comment]
Yeah, additionally the tests won't pass when installed with `python setup.py install`, it has to be installed with develop
