### ISSUE TITLE
buffer dtype mismatch

### ISSUE THREAD

**Issue by learningbymodeling** [scikit-learn-contrib/hdbscan#71]
I am trying to run hdbscan but I get the error:

> ValueError: Buffer dtype mismatch, expected 'double_t' but got 'long long'

I have attached my code below, it is standard from the example I have seen. Not sure how to proceed. 
Thank you
```
import hdbscan
hdb = hdbscan.HDBSCAN(algorithm='prims_balltree',min_cluster_size=10)
clusters_hdb = hdb.fit_predict(feature_vects)
```

**Comment by lmcinnes** [comment]
I think I need a little more information. Can you post the full stack trace that occurs at the error? Or possibly share the dataset that is failing?

**Comment by learningbymodeling** [comment]
Does this help? Thanks.
> Traceback (most recent call last):
> 
>   File "<ipython-input-113-ae6050d3b547>", line 2, in <module>
>     clusters_hdb = hdb.fit_predict(feature_vects)
> 
>   File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 750, in fit_predict
>     self.fit(X)
> 
>   File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 732, in fit
>     self._min_spanning_tree) = hdbscan(X, **kwargs)
> 
>   File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 507, in hdbscan
>     gen_min_span_tree, **kwargs)
> 
>   File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\externals\joblib\memory.py", line 283, in __call__
>     return self.func(*args, **kwargs)
> 
>   File "C:\Program Files\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 196, in _hdbscan_prims_kdtree
>     min_spanning_tree = mst_linkage_core_vector(X, core_distances, dist_metric, alpha)
> 
>   File "hdbscan/_hdbscan_linkage.pyx", line 51, in hdbscan._hdbscan_linkage.mst_linkage_core_vector (hdbscan\_hdbscan_linkage.c:3840)
> 
> ValueError: Buffer dtype mismatch, expected 'double_t' but got 'long long'

**Comment by lmcinnes** [comment]
Is it possible that your feature vectors are all integer valued? Can you
try casting it to float64? e.g.

    clusters_hdb = hdb.fit_predict(feature_vects.astype(np.float64))

Let me know if that works. That sort of casting *should* be happening
internally, and you shouldn't have know or worry about the type of your
input data, but perhaps a check/conversion is missing.

**Comment by edgarriba** [comment]
@lmcinnes 
> Let me know if that works. That sort of casting should be happening
internally, and you shouldn't have know or worry about the type of your
input data, but perhaps a check/conversion is missing.

I give faith that this issue is still there at least in the last pip package - I had to cast my `uchar` vectors to `np.float64`

**Comment by lmcinnes** [comment]
Sorry about that -- it fell off my radar. Should be fixed now, and I'll try to get a new pip package out soon to remedy the problem globally. Thanks for the heads up that I had missed this one.

**Comment by VarIr** [comment]
The dtype mismatch still seems to be an issue with `metric='precomputed'`. I get the error on fitting an `np.float32` distance matrix, but casting to `np.float64` fixes the problem.

**Comment by lmcinnes** [comment]
I'll see if I can hunt that down. Sorry about the issue, but I'm glad that at least casting can provide a workaround for now.

**Comment by jerrykaplan** [comment]
FYI same problem 8/6/2019 with integer input and metric='precomputed'. Casting to float64 fixed.

**Comment by mhaythornthwaite** [comment]
I had a similar error message when trying to run `hdbscan.validity_index()` and also fixed through casting my input X array from float32 to float64 `X = X.astype(np.float64)`. Thanks all!
